version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: python-onliner
    restart: unless-stopped
    ports:
     - "8000:8000"
    networks:
      - default
